saleor/saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.product_details, name='product-details'),
    url(r'^(?P<pk>[0-9]+)/publish/$',
        views.product_toggle_is_published, name='product-publish'),
    url(r'^add/select-type/$',
        views.product_select_type, name='product-add-select-type'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),
    url(r'^bulk-update/$',
        views.product_bulk_update, name='product-bulk-update'),
    url(r'^ajax/products/$',
        views.ajax_products_list, name='ajax-products'),

    url(r'^types/$',
        views.product_type_list, name='product-type-list'),
    url(r'^types/add/$',
        views.product_type_create, name='product-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$',
        views.product_type_edit, name='product-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$',
        views.product_type_delete, name='product-type-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_create, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),
    url(r'^ajax/variants/$',
        views.ajax_available_variants_list, name='ajax-available-variants'),

    url(r'^(?P<product_pk>[0-9]+)/images/$',
        views.product_images, name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_create, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url(r'^(?P<product_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_product_images, name='product-images-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_details, name='attribute-details'),
    url(r'attributes/add/$',
        views.attribute_create, name='attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$',
        views.attribute_value_create,
        name='attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$',  # noqa
        views.attribute_value_edit,
        name='attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',  # noqa
        views.attribute_value_delete,
        name='attribute-value-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$',
        views.ajax_reorder_attribute_values,
        name='attribute-values-reorder')]

saleor/saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name='add-to-cart'),
    url(r'^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$',
        views.collection_index, name='collection')]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import (
    cart_urlpatterns as cart_urls, checkout_urlpatterns as checkout_urls)
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from django.contrib import admin
 
handler404 = 'saleor.core.views.handle_404'

non_translatable_urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(GraphQLView.as_view(
        schema=schema)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))]

translatable_urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^page/', include((page_urls, 'page'), namespace='page')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search'))]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            '/media/', document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

saleor/saleor/dashboard/product/views.py
from datetime import date

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, reverse
from django.template.response import TemplateResponse
from django.utils.translation import npgettext_lazy, pgettext_lazy
from django.views.decorators.http import require_POST

from . import forms
from ...core.utils import get_paginator_items
from ...discount.models import Sale
from ...product.models import (
    Attribute, AttributeValue, Product, ProductImage, ProductType,
    ProductVariant)
from ...product.utils.availability import get_availability
from ...product.utils.costs import (
    get_margin_for_variant, get_product_costs_data)
from ..views import staff_member_required
from .filters import AttributeFilter, ProductFilter, ProductTypeFilter


@staff_member_required
@permission_required('product.manage_products')
def product_list(request):
    products = Product.objects.prefetch_related('images')
    products = products.order_by('name')
    product_types = ProductType.objects.all()
    product_filter = ProductFilter(request.GET, queryset=products)
    products = get_paginator_items(
        product_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'bulk_action_form': forms.ProductBulkUpdate(),
        'products': products, 'product_types': product_types,
        'filter_set': product_filter,
        'is_empty': not product_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/product/list.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def product_details(request, pk):
    products = Product.objects.prefetch_related('variants', 'images').all()
    product = get_object_or_404(products, pk=pk)
    variants = product.variants.all()
    images = product.images.all()
    availability = get_availability(
        product, discounts=request.discounts, taxes=request.taxes)
    sale_price = availability.price_range_undiscounted
    discounted_price = availability.price_range
    purchase_cost, margin = get_product_costs_data(product)

    # no_variants is True for product types that doesn't require variant.
    # In this case we're using the first variant under the hood to allow stock
    # management.
    no_variants = not product.product_type.has_variants
    only_variant = variants.first() if no_variants else None
    ctx = {
        'product': product, 'sale_price': sale_price,
        'discounted_price': discounted_price, 'variants': variants,
        'images': images, 'no_variants': no_variants,
        'only_variant': only_variant, 'purchase_cost': purchase_cost,
        'margin': margin, 'is_empty': not variants.exists()}
    return TemplateResponse(request, 'dashboard/product/detail.html', ctx)


@require_POST
@staff_member_required
@permission_required('product.manage_products')
def product_toggle_is_published(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_published = not product.is_published
    product.save(update_fields=['is_published'])
    return JsonResponse(
        {'success': True, 'is_published': product.is_published})


@staff_member_required
@permission_required('product.manage_products')
def product_select_type(request):
    """View for add product modal embedded in the product list view."""
    form = forms.ProductTypeSelectorForm(request.POST or None)
    status = 200
    if form.is_valid():
        redirect_url = reverse(
            'dashboard:product-add',
            kwargs={'type_pk': form.cleaned_data.get('product_type').pk})
        return (
            JsonResponse({'redirectUrl': redirect_url})
            if request.is_ajax() else redirect(redirect_url))
    elif form.errors:
        status = 400
    ctx = {'form': form}
    template = 'dashboard/product/modal/select_type.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.manage_products')
def product_create(request, type_pk):
    track_inventory = request.site.settings.track_inventory_by_default
    product_type = get_object_or_404(ProductType, pk=type_pk)
    create_variant = not product_type.has_variants
    product = Product()
    product.product_type = product_type
    product_form = forms.ProductForm(request.POST or None, instance=product)
    if create_variant:
        variant = ProductVariant(
            product=product, track_inventory=track_inventory)
        variant_form = forms.ProductVariantForm(
            request.POST or None,
            instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if product_form.is_valid() and not variant_errors:
        product = product_form.save()
        if create_variant:
            variant.product = product
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-details', pk=product.pk)
    ctx = {
        'product_form': product_form, 'variant_form': variant_form,
        'product': product}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def product_edit(request, pk):
    product = get_object_or_404(
        Product.objects.prefetch_related('variants'), pk=pk)
    form = forms.ProductForm(request.POST or None, instance=product)

    edit_variant = not product.product_type.has_variants
    if edit_variant:
        variant = product.variants.first()
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if form.is_valid() and not variant_errors:
        product = form.save()
        if edit_variant:
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-details', pk=product.pk)
    ctx = {
        'product': product, 'product_form': form, 'variant_form': variant_form}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        msg = pgettext_lazy(
            'Dashboard message', 'Removed product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-list')
    return TemplateResponse(
        request,
        'dashboard/product/modal/confirm_delete.html',
        {'product': product})


@require_POST
@staff_member_required
@permission_required('product.manage_products')
def product_bulk_update(request):
    form = forms.ProductBulkUpdate(request.POST)
    if form.is_valid():
        form.save()
        count = len(form.cleaned_data['products'])
        msg = npgettext_lazy(
            'Dashboard message',
            '%(count)d product has been updated',
            '%(count)d products have been updated',
            number='count') % {'count': count}
        messages.success(request, msg)
    return redirect('dashboard:product-list')


@staff_member_required
def ajax_products_list(request):
    """Return products filtered by request GET parameters.

    Response format is that of a Select2 JS widget.
    """
    queryset = (
        Product.objects.all()
        if request.user.has_perm('product.manage_products')
        else Product.objects.available_products())
    search_query = request.GET.get('q', '')
    if search_query:
        queryset = queryset.filter(Q(name__icontains=search_query))
    products = [
        {'id': product.id, 'text': str(product)} for product in queryset]
    return JsonResponse({'results': products})


@staff_member_required
@permission_required('product.manage_products')
def product_type_list(request):
    types = ProductType.objects.all().prefetch_related(
        'product_attributes', 'variant_attributes').order_by('name')
    type_filter = ProductTypeFilter(request.GET, queryset=types)
    types = get_paginator_items(
        type_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    types.object_list = [
        (pt.pk, pt.name, pt.product_attributes.all(),
         pt.variant_attributes.all()) for pt in types.object_list]
    ctx = {
        'product_types': types, 'filter_set': type_filter,
        'is_empty': not type_filter.queryset.exists()}
    return TemplateResponse(
        request,
        'dashboard/product/product_type/list.html',
        ctx)


@staff_member_required
@permission_required('product.manage_products')
def product_type_create(request):
    product_type = ProductType()
    form = forms.ProductTypeForm(request.POST or None, instance=product_type)
    if form.is_valid():
        product_type = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product type %s') % (product_type,)
        messages.success(request, msg)
        return redirect('dashboard:product-type-list')
    ctx = {'form': form, 'product_type': product_type}
    return TemplateResponse(
        request,
        'dashboard/product/product_type/form.html',
        ctx)


@staff_member_required
@permission_required('product.manage_products')
def product_type_edit(request, pk):
    product_type = get_object_or_404(ProductType, pk=pk)
    form = forms.ProductTypeForm(request.POST or None, instance=product_type)
    if form.is_valid():

saleor/templates/dashboard/product/attribute/detail.html
{% extends 'dashboard/base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
  {{ attribute }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-attribute{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:attributes' %}" class="breadcrumbs--ellipsed-item">
      {% trans "Attributes" context "Attribute detail breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:attributes' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ attribute }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}

  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ attribute.name }}
          </span>
          {% if product_type %}
            {% trans "Product type" %}: <a href="{% url "dashboard:product-type-update" pk=product_type.pk %}">{{ product_type }}</a>
          {% elif attribute.pk %}
            <a href="{% url "dashboard:product-type-list" %}">Assign to a product type</a>
          {% endif %}
        </div>
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url "dashboard:attribute-update" attribute.pk %}">
            {% trans "Edit attribute" context "Attribute detail action" %}
          </a>
          <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:attribute-delete' pk=attribute.pk %}">
            {% trans "Remove attribute" context "Attribute detail action" %}
          </a>
        </div>
      </div>
    </div>
    <div class="col s12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{% trans "Attribute values" %}</span>
        </div>
        <div class="data-table-header-action">
          <a href="{% url 'dashboard:attribute-value-add' attribute_pk=attribute.pk %}" class="btn-flat waves-effect">
            {% trans "Add" %}
          </a>
        </div>
        <div class="data-table-container">
          <table class="bordered highlight responsive data-table">
            <thead>
              <tr>
                <th class="data-table-icon"></th>

                <th>{% trans "Display name" %}</th>
                <th></th>
              </tr>
            </thead>
            <tbody class="sortable-items" data-post-url="{% url 'dashboard:attribute-values-reorder' attribute_pk=attribute.pk %}" data-post-name="ordered_values">
              {% for value in values %}
                <tr class="sortable-item" data-id="{{ value.pk }}">
                  <td class="data-table-icon ignore-link sortable__drag-area">
                    <svg data-src="{% static "dashboard/images/reorder.svg" %}" height="20" width="20" fill="#000" />
                  </td>
                  <td>
                    {{ value.name }}
                  </td>
                  <td class="right-align">
                    <a href="{% url 'dashboard:attribute-value-update' attribute_pk=attribute.pk value_pk=value.pk %}" class="btn-flat waves-effect">
                      {% trans 'Edit' context 'Attribute value edit action' %}
                    </a>
                    <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:attribute-value-delete' attribute_pk=attribute.pk value_pk=value.pk %}">
                      {% trans 'Remove' context 'Attribute value edit action' %}
                    </a>
                  </td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="2">{% trans "No attribute values" context "Empty list of attribute values" %}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/attribute/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if attribute.pk %}
   {% trans "Edit" context "Dashboard attributes list" %} - {{ attribute }}
  {% else %}
    {% trans "Add new attribute" context "Attribute detail page title" %}
  {% endif %}
  - {{ block.super }}
{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:attributes" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}


{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:attributes' %}" class="breadcrumbs--ellipsed-item">
        {% trans "Attributes" context "Dashboard attributes list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:attributes' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if attribute.pk %}
    <li>
      <a href="{% url 'dashboard:attribute-details' attribute.pk %}" class="breadcrumbs--ellipsed-item">
        {{ attribute }}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "Attribute detail breadcrumbs" %}
      </span>
    </li>
    {% else %}
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Add new attribute" context "Attribute detail breadcrumbs" %}
      </span>
    </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-attributes" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            <div class="row">
              {{ form.name|materializecss }}
            </div>
            <div class="row">
              {{ form.slug|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            {% if attribute.pk %}
              <a href="{% url 'dashboard:attribute-details' attribute.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:attributes' %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/attribute/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Attributes" context "Dashboard attributes list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a class="btn-fab-default waves-effect waves-light" href="{% url 'dashboard:attribute-add' %}" title="{% trans "Add attribute" context "Attribute list add button text" %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Attributes" context "Dashboard attributes list" %}
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if attributes %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight data-table data-table-description">
              <thead>
                <tr>
                  {% trans "Name" context "Dashboard attributes list table header name" as label %}
                  {% sorting_header 'name' label %}
                  <th>{% trans "Product type" context "Name of product type related to the attribute" %}</th>
                  <th>
                    {% trans "Values" context "Dashboard attributes list table header values" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for pk, name, product_type, values in attributes %}
                  <tr data-action-go="{% url 'dashboard:attribute-details' pk=pk %}">
                    <td>
                      {{ name }}
                    </td>
                    <td>
                      {{ product_type|default:'-' }}
                    </td>
                    <td>
                      {% if values %}{{ values|join:", " }}{% else %}-{% endif %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% paginate attributes %}
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/product/attribute/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No attributes found." context "Empty attribute list message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/attribute/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No attributes found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Attributes are used to define custom properties of products and variants, that can be used for filtering purposes in the storefront.<br>
    You can add attributes by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}" /></span> button.
  {% endblocktrans %}
{% endblock %}